sudo: required
services:
  - docker

before_install:
  - docker image build -t partha00011/frontend-docker-travis -f Dockerfile.dev .

script:
  #- docker container run partha00011/frontend-docker-travis npm run test -- --coverage
  - docker container run -e CI=true partha00011/frontend-docker-travis npm run test